name: CI-CD FOR LIVE ENV

on:
  workflow_dispatch:

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm  ci
      - name: Run tests
        run: npm run test

  Styling_and_security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Run formating and linting checks and code security check
        run: |
          npm run check-format
          npm run lint

  Live-deployment:
    needs: [Tests, Styling_and_security]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: DOCKER - Login, build and push to hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
          docker build . --target=production -t ${{secrets.DOCKER_USERNAME}}/password-generator-app:LIVE-${{github.sha}}
          docker push  ${{secrets.DOCKER_USERNAME}}/password-generator-app:LIVE-${{github.sha}}

      - name: SSH into EC2 and run docker image
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{secrets.EC2_HOST_LIVE}}
          key: ${{secrets.EC2_KEY}}
          username: ${{secrets.EC2_USERNAME}}
          script: |
            sudo yum update -y
            sudo yum install -y docker
            sudo service docker start || true
            sudo docker stop app-live || true
            sudo docker rm app-live || true
            sudo docker pull ${{secrets.DOCKER_USERNAME}}/password-generator-app:LIVE-${{github.sha}}
            sudo docker run -d --name app-live -p 3000:3000 ${{secrets.DOCKER_USERNAME}}/password-generator-app:LIVE-${{github.sha}}
